// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

package timezones

type Timezones struct {
	supportedZones []Timezone
}

func New() *Timezones {
	timezones := Timezones{}

	timezones.supportedZones = DefaultSupportedTimezone

	return &timezones
}

func (t *Timezones) GetSupported() []Timezone {
	return t.supportedZones
}

func DefaultUserTimezone() map[string]string {
	defaultTimezone := make(map[string]string)
	defaultTimezone["useAutomaticTimezone"] = "true"
	defaultTimezone["automaticTimezone"] = ""
	defaultTimezone["manualTimezone"] = ""

	return defaultTimezone
}

type Timezone struct {
	Offset float64 `json:"offset"`
	IsDST bool   `json:"is_dst"`
	Group string `json:"group"`
	UTC []string `json:"utc"`
}

var DefaultSupportedTimezone = []Timezone{
    {
        Offset: -12,
        IsDST: false,
        Group: "International Date Line West",
        UTC: []string{"Etc/GMT+12"},
    },
    {
        Offset: -11,
        IsDST: false,
        Group: "Coordinated Universal Time-11",
        UTC: []string{
            "Etc/GMT+11",
            "Pacific/Midway",
            "Pacific/Niue",
            "Pacific/Pago_Pago",
        },
    },
    {
        Offset: -10,
        IsDST: false,
        Group: "Hawaii",
        UTC: []string{
            "Etc/GMT+10",
            "Pacific/Honolulu",
            "Pacific/Johnston",
            "Pacific/Rarotonga",
            "Pacific/Tahiti",
        },
    },
    {
        Offset: -8,
        IsDST: true,
        Group: "Alaska",
        UTC: []string{
            "America/Anchorage",
            "America/Juneau",
            "America/Nome",
            "America/Sitka",
            "America/Yakutat",
        },
    },
    {
        Offset: -7,
        IsDST: false,
        Group: "Arizona",
        UTC: []string{
            "America/Creston",
            "America/Dawson_Creek",
            "America/Hermosillo",
            "America/Phoenix",
            "Etc/GMT+7",
        },
    },
    {
        Offset: -7,
        IsDST: true,
        Group: "Baja California",
        UTC: []string{"America/Santa_Isabel"},
    },
    {
        Offset: -7,
        IsDST: false,
        Group: "Chihuahua, La Paz, Mazatlan",
        UTC: []string{"America/Chihuahua", "America/Mazatlan"},
    },
    {
        Offset: -7,
        IsDST: true,
        Group: "Pacific Time (US & Canada)",
        UTC: []string{
            "America/Dawson",
            "America/Los_Angeles",
            "America/Tijuana",
            "America/Vancouver",
            "America/Whitehorse",
            "PST8PDT",
        },
    },
    {
        Offset: -6,
        IsDST: false,
        Group: "Central America",
        UTC: []string{
            "America/Belize",
            "America/Costa_Rica",
            "America/El_Salvador",
            "America/Guatemala",
            "America/Managua",
            "America/Tegucigalpa",
            "Etc/GMT+6",
            "Pacific/Galapagos",
        },
    },
    {
        Offset: -6,
        IsDST: false,
        Group: "Guadalajara, Mexico City, Monterrey",
        UTC: []string{
            "America/Bahia_Banderas",
            "America/Merida",
            "America/Mexico_City",
            "America/Monterrey",
        },
    },
    {
        Offset: -6,
        IsDST: true,
        Group: "Mountain Time (US & Canada)",
        UTC: []string{
            "America/Boise",
            "America/Cambridge_Bay",
            "America/Denver",
            "America/Edmonton",
            "America/Inuvik",
            "America/Ojinaga",
            "America/Yellowknife",
            "MST7MDT",
        },
    },
    {
        Offset: -6,
        IsDST: false,
        Group: "Saskatchewan",
        UTC: []string{"America/Regina", "America/Swift_Current"},
    },
    {
        Offset: -5,
        IsDST: false,
        Group: "Bogota, Lima, Quito",
        UTC: []string{
            "America/Bogota",
            "America/Cayman",
            "America/Coral_Harbour",
            "America/Eirunepe",
            "America/Guayaquil",
            "America/Jamaica",
            "America/Lima",
            "America/Panama",
            "America/Rio_Branco",
            "Etc/GMT+5",
        },
    },
    {
        Offset: -5,
        IsDST: true,
        Group: "Central Time (US & Canada)",
        UTC: []string{
            "America/Chicago",
            "America/Indiana/Knox",
            "America/Indiana/Tell_City",
            "America/Matamoros",
            "America/Menominee",
            "America/North_Dakota/Beulah",
            "America/North_Dakota/Center",
            "America/North_Dakota/New_Salem",
            "America/Rainy_River",
            "America/Rankin_Inlet",
            "America/Resolute",
            "America/Winnipeg",
            "CST6CDT",
        },
    },
    {
        Offset: -4,
        IsDST: false,
        Group: "Caracas",
        UTC: []string{"America/Caracas"},
    },
    {
        Offset: -4,
        IsDST: false,
        Group: "Cuiaba",
        UTC: []string{"America/Campo_Grande", "America/Cuiaba"},
    },
    {
        Offset: -4,
        IsDST: true,
        Group: "Eastern Time (US & Canada)",
        UTC: []string{
            "America/Detroit",
            "America/Havana",
            "America/Indiana/Petersburg",
            "America/Indiana/Vincennes",
            "America/Indiana/Winamac",
            "America/Iqaluit",
            "America/Kentucky/Monticello",
            "America/Louisville",
            "America/Montreal",
            "America/Nassau",
            "America/New_York",
            "America/Nipigon",
            "America/Pangnirtung",
            "America/Port-au-Prince",
            "America/Thunder_Bay",
            "America/Toronto",
            "EST5EDT",
        },
    },
    {
        Offset: -4,
        IsDST: false,
        Group: "Georgetown, La Paz, Manaus, San Juan",
        UTC: []string{
            "America/Anguilla",
            "America/Antigua",
            "America/Aruba",
            "America/Barbados",
            "America/Blanc-Sablon",
            "America/Boa_Vista",
            "America/Curacao",
            "America/Dominica",
            "America/Grenada",
            "America/Guadeloupe",
            "America/Guyana",
            "America/Kralendijk",
            "America/La_Paz",
            "America/Lower_Princes",
            "America/Manaus",
            "America/Marigot",
            "America/Martinique",
            "America/Montserrat",
            "America/Port_of_Spain",
            "America/Porto_Velho",
            "America/Puerto_Rico",
            "America/Santo_Domingo",
            "America/St_Barthelemy",
            "America/St_Kitts",
            "America/St_Lucia",
            "America/St_Thomas",
            "America/St_Vincent",
            "America/Tortola",
            "Etc/GMT+4",
        },
    },
    {
        Offset: -4,
        IsDST: true,
        Group: "Indiana (East)",
        UTC: []string{
            "America/Indiana/Marengo",
            "America/Indiana/Vevay",
            "America/Indianapolis",
        },
    },
    {
        Offset: -3,
        IsDST: true,
        Group: "Asuncion",
        UTC: []string{"America/Asuncion"},
    },
    {
        Offset: -3,
        IsDST: true,
        Group: "Atlantic Time (Canada)",
        UTC: []string{
            "America/Glace_Bay",
            "America/Goose_Bay",
            "America/Halifax",
            "America/Moncton",
            "America/Thule",
            "Atlantic/Bermuda",
        },
    },
    {
        Offset: -3,
        IsDST: false,
        Group: "Brasilia",
        UTC: []string{"America/Sao_Paulo"},
    },
    {
        Offset: -3,
        IsDST: false,
        Group: "Buenos Aires",
        UTC: []string{
            "America/Argentina/La_Rioja",
            "America/Argentina/Rio_Gallegos",
            "America/Argentina/Salta",
            "America/Argentina/San_Juan",
            "America/Argentina/San_Luis",
            "America/Argentina/Tucuman",
            "America/Argentina/Ushuaia",
            "America/Buenos_Aires",
            "America/Catamarca",
            "America/Cordoba",
            "America/Jujuy",
            "America/Mendoza",
        },
    },
    {
        Offset: -3,
        IsDST: false,
        Group: "Cayenne, Fortaleza",
        UTC: []string{
            "America/Araguaina",
            "America/Belem",
            "America/Cayenne",
            "America/Fortaleza",
            "America/Maceio",
            "America/Paramaribo",
            "America/Recife",
            "America/Santarem",
            "Antarctica/Rothera",
            "Atlantic/Stanley",
            "Etc/GMT+3",
        },
    },
    {
        Offset: -3,
        IsDST: false,
        Group: "Greenland",
        UTC: []string{"America/Godthab"},
    },
    {
        Offset: -3,
        IsDST: false,
        Group: "Montevideo",
        UTC: []string{"America/Montevideo"},
    },
    {
        Offset: -3,
        IsDST: false,
        Group: "Salvador",
        UTC: []string{"America/Bahia"},
    },
    {
        Offset: -3,
        IsDST: true,
        Group: "Santiago",
        UTC: []string{"America/Santiago"},
    },
    {
        Offset: -2.5,
        IsDST: true,
        Group: "Newfoundland",
        UTC: []string{"America/St_Johns"},
    },
    {
        Offset: -2,
        IsDST: false,
        Group: "Coordinated Universal Time-02",
        UTC: []string{"America/Noronha", "Atlantic/South_Georgia", "Etc/GMT+2"},
    },
    {
        Offset: -1,
        IsDST: false,
        Group: "Azores",
        UTC: []string{"America/Scoresbysund", "Atlantic/Azores"},
    },
    {
        Offset: -1,
        IsDST: false,
        Group: "Cape Verde Is.",
        UTC: []string{"Atlantic/Cape_Verde", "Etc/GMT+1"},
    },
    {
        Offset: 0,
        IsDST: false,
        Group: "Coordinated Universal Time",
        UTC: []string{"America/Danmarkshavn", "Etc/GMT"},
    },
    {
        Offset: 0,
        IsDST: false,
        Group: "Dublin, Lisbon",
        UTC: []string{
            "Atlantic/Canary",
            "Atlantic/Faeroe",
            "Atlantic/Madeira",
            "Europe/Dublin",
            "Europe/Lisbon",
        },
    },
    {
        Offset: 0,
        IsDST: false,
        Group: "Edinburgh, London",
        UTC: []string{
            "Europe/Isle_of_Man",
            "Europe/Guernsey",
            "Europe/Jersey",
            "Europe/London",
        },
    },
    {
        Offset: 0,
        IsDST: false,
        Group: "Monrovia, Reykjavik",
        UTC: []string{
            "Africa/Abidjan",
            "Africa/Accra",
            "Africa/Bamako",
            "Africa/Banjul",
            "Africa/Bissau",
            "Africa/Conakry",
            "Africa/Dakar",
            "Africa/Freetown",
            "Africa/Lome",
            "Africa/Monrovia",
            "Africa/Nouakchott",
            "Africa/Ouagadougou",
            "Africa/Sao_Tome",
            "Atlantic/Reykjavik",
            "Atlantic/St_Helena",
        },
    },
    {
        Offset: 1,
        IsDST: false,
        Group: "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
        UTC: []string{
            "Arctic/Longyearbyen",
            "Europe/Amsterdam",
            "Europe/Andorra",
            "Europe/Berlin",
            "Europe/Busingen",
            "Europe/Gibraltar",
            "Europe/Luxembourg",
            "Europe/Malta",
            "Europe/Monaco",
            "Europe/Oslo",
            "Europe/Rome",
            "Europe/San_Marino",
            "Europe/Stockholm",
            "Europe/Vaduz",
            "Europe/Vatican",
            "Europe/Vienna",
            "Europe/Zurich",
        },
    },
    {
        Offset: 1,
        IsDST: false,
        Group: "Belgrade, Bratislava, Budapest, Ljubljana, Prague",
        UTC: []string{
            "Europe/Belgrade",
            "Europe/Bratislava",
            "Europe/Budapest",
            "Europe/Ljubljana",
            "Europe/Podgorica",
            "Europe/Prague",
            "Europe/Tirane",
        },
    },
    {
        Offset: 1,
        IsDST: false,
        Group: "Brussels, Copenhagen, Madrid, Paris",
        UTC: []string{
            "Africa/Ceuta",
            "Europe/Brussels",
            "Europe/Copenhagen",
            "Europe/Madrid",
            "Europe/Paris",
        },
    },
    {
        Offset: 1,
        IsDST: false,
        Group: "Casablanca",
        UTC: []string{"Africa/Casablanca", "Africa/El_Aaiun"},
    },
    {
        Offset: 1,
        IsDST: false,
        Group: "Sarajevo, Skopje, Warsaw, Zagreb",
        UTC: []string{
            "Europe/Sarajevo",
            "Europe/Skopje",
            "Europe/Warsaw",
            "Europe/Zagreb",
        },
    },
    {
        Offset: 1,
        IsDST: false,
        Group: "West Central Africa",
        UTC: []string{
            "Africa/Algiers",
            "Africa/Bangui",
            "Africa/Brazzaville",
            "Africa/Douala",
            "Africa/Kinshasa",
            "Africa/Lagos",
            "Africa/Libreville",
            "Africa/Luanda",
            "Africa/Malabo",
            "Africa/Ndjamena",
            "Africa/Niamey",
            "Africa/Porto-Novo",
            "Africa/Tunis",
            "Etc/GMT-1",
        },
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Amman",
        UTC: []string{"Asia/Amman"},
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Athens, Bucharest",
        UTC: []string{
            "Asia/Nicosia",
            "Europe/Athens",
            "Europe/Bucharest",
            "Europe/Chisinau",
        },
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Beirut",
        UTC: []string{"Asia/Beirut"},
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Cairo",
        UTC: []string{"Africa/Cairo"},
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Damascus",
        UTC: []string{"Asia/Damascus"},
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Harare, Pretoria",
        UTC: []string{
            "Africa/Blantyre",
            "Africa/Bujumbura",
            "Africa/Gaborone",
            "Africa/Harare",
            "Africa/Johannesburg",
            "Africa/Kigali",
            "Africa/Lubumbashi",
            "Africa/Lusaka",
            "Africa/Maputo",
            "Africa/Maseru",
            "Africa/Mbabane",
            "Etc/GMT-2",
        },
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
        UTC: []string{
            "Europe/Helsinki",
            "Europe/Kiev",
            "Europe/Mariehamn",
            "Europe/Riga",
            "Europe/Sofia",
            "Europe/Tallinn",
            "Europe/Uzhgorod",
            "Europe/Vilnius",
            "Europe/Zaporozhye",
        },
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Jerusalem",
        UTC: []string{"Asia/Jerusalem"},
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Kaliningrad",
        UTC: []string{"Europe/Kaliningrad"},
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Tripoli",
        UTC: []string{"Africa/Tripoli"},
    },
    {
        Offset: 2,
        IsDST: false,
        Group: "Windhoek",
        UTC: []string{"Africa/Windhoek"},
    },
    {
        Offset: 3,
        IsDST: false,
        Group: "Baghdad",
        UTC: []string{"Asia/Baghdad"},
    },
    {
        Offset: 3,
        IsDST: false,
        Group: "Istanbul",
        UTC: []string{"Europe/Istanbul"},
    },
    {
        Offset: 3,
        IsDST: false,
        Group: "Kuwait, Riyadh",
        UTC: []string{
            "Asia/Aden",
            "Asia/Bahrain",
            "Asia/Kuwait",
            "Asia/Qatar",
            "Asia/Riyadh",
        },
    },
    {
        Offset: 3,
        IsDST: false,
        Group: "Moscow, St. Petersburg",
        UTC: []string{"Europe/Kirov", "Europe/Moscow", "Europe/Simferopol"},
    },
    {
        Offset: 3,
        IsDST: false,
        Group: "Nairobi",
        UTC: []string{
            "Africa/Addis_Ababa",
            "Africa/Asmera",
            "Africa/Dar_es_Salaam",
            "Africa/Djibouti",
            "Africa/Juba",
            "Africa/Kampala",
            "Africa/Mogadishu",
            "Africa/Nairobi",
            "Antarctica/Syowa",
            "Etc/GMT-3",
            "Indian/Antananarivo",
            "Indian/Comoro",
            "Indian/Mayotte",
        },
    },
    {
        Offset: 3.5,
        IsDST: false,
        Group: "Tehran",
        UTC: []string{"Asia/Tehran"},
    },
    {
        Offset: 4,
        IsDST: false,
        Group: "Abu Dhabi, Muscat",
        UTC: []string{"Asia/Dubai", "Asia/Muscat", "Etc/GMT-4"},
    },
    {
        Offset: 4,
        IsDST: false,
        Group: "Baku",
        UTC: []string{"Asia/Baku"},
    },
    {
        Offset: 4,
        IsDST: false,
        Group: "Port Louis",
        UTC: []string{"Indian/Mahe", "Indian/Mauritius", "Indian/Reunion"},
    },
    {
        Offset: 4,
        IsDST: false,
        Group: "Samara, Ulyanovsk, Saratov",
        UTC: []string{"Europe/Astrakhan", "Europe/Samara", "Europe/Ulyanovsk"},
    },
    {
        Offset: 4,
        IsDST: false,
        Group: "Tbilisi",
        UTC: []string{"Asia/Tbilisi"},
    },
    {
        Offset: 4,
        IsDST: false,
        Group: "Yerevan",
        UTC: []string{"Asia/Yerevan"},
    },
    {
        Offset: 4.5,
        IsDST: false,
        Group: "Kabul",
        UTC: []string{"Asia/Kabul"},
    },
    {
        Offset: 5,
        IsDST: false,
        Group: "Ashgabat, Tashkent",
        UTC: []string{
            "Antarctica/Mawson",
            "Asia/Aqtau",
            "Asia/Aqtobe",
            "Asia/Ashgabat",
            "Asia/Dushanbe",
            "Asia/Oral",
            "Asia/Samarkand",
            "Asia/Tashkent",
            "Etc/GMT-5",
            "Indian/Kerguelen",
            "Indian/Maldives",
        },
    },
    {
        Offset: 5,
        IsDST: false,
        Group: "Islamabad, Karachi",
        UTC: []string{"Asia/Karachi"},
    },
    {
        Offset: 5,
        IsDST: false,
        Group: "Yekaterinburg",
        UTC: []string{"Asia/Yekaterinburg"},
    },
    {
        Offset: 5.5,
        IsDST: false,
        Group: "Chennai, Kolkata, Mumbai, New Delhi",
        UTC: []string{"Asia/Kolkata"},
    },
    {
        Offset: 5.5,
        IsDST: false,
        Group: "Sri Jayawardenepura",
        UTC: []string{"Asia/Colombo"},
    },
    {
        Offset: 5.75,
        IsDST: false,
        Group: "Kathmandu",
        UTC: []string{"Asia/Kathmandu"},
    },
    {
        Offset: 6,
        IsDST: false,
        Group: "Astana",
        UTC: []string{
            "Antarctica/Vostok",
            "Asia/Almaty",
            "Asia/Bishkek",
            "Asia/Urumqi",
            "Etc/GMT-6",
            "Indian/Chagos",
        },
    },
    {
        Offset: 6,
        IsDST: false,
        Group: "Dhaka",
        UTC: []string{"Asia/Dhaka", "Asia/Thimphu"},
    },
    {
        Offset: 6,
        IsDST: false,
        Group: "Novokuznetsk, Omsk",
        UTC: []string{"Asia/Omsk"},
    },
    {
        Offset: 6.5,
        IsDST: false,
        Group: "Yangon (Rangoon)",
        UTC: []string{"Asia/Rangoon", "Indian/Cocos"},
    },
    {
        Offset: 7,
        IsDST: false,
        Group: "Bangkok, Hanoi, Jakarta",
        UTC: []string{
            "Antarctica/Davis",
            "Asia/Bangkok",
            "Asia/Hovd",
            "Asia/Jakarta",
            "Asia/Phnom_Penh",
            "Asia/Pontianak",
            "Asia/Saigon",
            "Asia/Vientiane",
            "Etc/GMT-7",
            "Indian/Christmas",
        },
    },
    {
        Offset: 7,
        IsDST: false,
        Group: "Krasnoyarsk",
        UTC: []string{"Asia/Krasnoyarsk"},
    },
    {
        Offset: 7,
        IsDST: false,
        Group: "Novosibirsk",
        UTC: []string{"Asia/Novosibirsk", "Asia/Novokuznetsk"},
    },
    {
        Offset: 8,
        IsDST: false,
        Group: "Beijing, Chongqing, Hong Kong, Urumqi",
        UTC: []string{"Asia/Hong_Kong", "Asia/Macau", "Asia/Shanghai"},
    },
    {
        Offset: 8,
        IsDST: false,
        Group: "Irkutsk",
        UTC: []string{"Asia/Irkutsk"},
    },
    {
        Offset: 8,
        IsDST: false,
        Group: "Kuala Lumpur, Singapore",
        UTC: []string{
            "Asia/Brunei",
            "Asia/Kuala_Lumpur",
            "Asia/Kuching",
            "Asia/Makassar",
            "Asia/Manila",
            "Asia/Singapore",
            "Etc/GMT-8",
        },
    },
    {
        Offset: 8,
        IsDST: false,
        Group: "Perth",
        UTC: []string{"Antarctica/Casey", "Australia/Perth"},
    },
    {
        Offset: 8,
        IsDST: false,
        Group: "Taipei",
        UTC: []string{"Asia/Taipei"},
    },
    {
        Offset: 8,
        IsDST: false,
        Group: "Ulaanbaatar",
        UTC: []string{"Asia/Choibalsan", "Asia/Ulaanbaatar"},
    },
    {
        Offset: 9,
        IsDST: false,
        Group: "Osaka, Sapporo, Tokyo",
        UTC: []string{
            "Asia/Dili",
            "Asia/Jayapura",
            "Asia/Tokyo",
            "Etc/GMT-9",
            "Pacific/Palau",
        },
    },
    {
        Offset: 9,
        IsDST: false,
        Group: "Seoul",
        UTC: []string{"Asia/Pyongyang", "Asia/Seoul"},
    },
    {
        Offset: 9,
        IsDST: false,
        Group: "Yakutsk",
        UTC: []string{"Asia/Chita", "Asia/Khandyga", "Asia/Yakutsk"},
    },
    {
        Offset: 9.5,
        IsDST: false,
        Group: "Darwin",
        UTC: []string{"Australia/Darwin"},
    },
    {
        Offset: 10,
        IsDST: false,
        Group: "Brisbane",
        UTC: []string{"Australia/Brisbane", "Australia/Lindeman"},
    },
    {
        Offset: 10,
        IsDST: false,
        Group: "Guam, Port Moresby",
        UTC: []string{
            "Antarctica/DumontDUrville",
            "Etc/GMT-10",
            "Pacific/Guam",
            "Pacific/Port_Moresby",
            "Pacific/Saipan",
            "Pacific/Truk",
        },
    },
    {
        Offset: 10,
        IsDST: false,
        Group: "Vladivostok",
        UTC: []string{"Asia/Ust-Nera", "Asia/Vladivostok"},
    },
    {
        Offset: 10.5,
        IsDST: true,
        Group: "Adelaide",
        UTC: []string{"Australia/Adelaide", "Australia/Broken_Hill"},
    },
    {
        Offset: 11,
        IsDST: true,
        Group: "Canberra, Melbourne, Sydney",
        UTC: []string{"Australia/Melbourne", "Australia/Sydney"},
    },
    {
        Offset: 11,
        IsDST: true,
        Group: "Hobart",
        UTC: []string{"Australia/Hobart"},
    },
    {
        Offset: 11,
        IsDST: false,
        Group: "Magadan",
        UTC: []string{"Asia/Magadan", "Asia/Srednekolymsk"},
    },
    {
        Offset: 11,
        IsDST: false,
        Group: "Sakhalin",
        UTC: []string{"Asia/Sakhalin"},
    },
    {
        Offset: 11,
        IsDST: false,
        Group: "Solomon Is., New Caledonia",
        UTC: []string{
            "Antarctica/Macquarie",
            "Etc/GMT-11",
            "Pacific/Efate",
            "Pacific/Guadalcanal",
            "Pacific/Kosrae",
            "Pacific/Noumea",
            "Pacific/Ponape",
        },
    },
    {
        Offset: 12,
        IsDST: false,
        Group: "Anadyr, Kamchatka",
        UTC: []string{"Asia/Anadyr", "Asia/Kamchatka"},
    },
    {
        Offset: 12,
        IsDST: false,
        Group: "Coordinated Universal Time+12",
        UTC: []string{
            "Etc/GMT-12",
            "Pacific/Funafuti",
            "Pacific/Kwajalein",
            "Pacific/Majuro",
            "Pacific/Nauru",
            "Pacific/Tarawa",
            "Pacific/Wake",
            "Pacific/Wallis",
        },
    },
    {
        Offset: 12,
        IsDST: false,
        Group: "Fiji",
        UTC: []string{"Pacific/Fiji"},
    },
    {
        Offset: 13,
        IsDST: true,
        Group: "Auckland, Wellington",
        UTC: []string{"Antarctica/McMurdo", "Pacific/Auckland"},
    },
    {
        Offset: 13,
        IsDST: false,
        Group: "Nuku'alofa",
        UTC: []string{
            "Etc/GMT-13",
            "Pacific/Enderbury",
            "Pacific/Fakaofo",
            "Pacific/Tongatapu",
        },
    },
    {
        Offset: 14,
        IsDST: true,
        Group: "Samoa",
        UTC: []string{"Pacific/Apia"},
    },
}
